---

- name: Install dependencies
  apt:
    name: '{{ item }}'
    update_cache: true
  with_items:
    - acl
    - git
    - build-essential
    - python2.7-dev
    - libffi-dev
    - python-pip
    - python-setuptools
    - sqlite3
    - libssl-dev
    - python-virtualenv
    - libjpeg-dev
    - libxslt1-dev

- name: Add go ppa
  apt_repository:
    repo: ppa:longsleep/golang-backports
    state: present
    update_cache: true

- name: Install golang
  apt:
    name: golang-go
    state: present


- name: Ensure riot user exists
  user:
    name: '{{ riot_user }}'

- name: Install n
  become: true
  become_user: '{{ riot_user }}'
  shell: curl -L https://git.io/n-install | SHELL=/bin/bash bash -s -- -y stable
  args:
    creates: '/home/{{ riot_user }}/n/bin/n'
    executable: /bin/bash
