---

- name: Install postgresql
  apt:
    pkg: '{{ item }}'
    update_cache: true
  with_items:
    - postgresql

- name: Install python-psycopg
  pip:
    name: psycopg2
  become: true

- name: Create database user
  postgresql_user:
    name: '{{ synapse_db_user }}'
    password: '{{ synapse_db_pass }}'
    encrypted: true
    state: present
    fail_on_user: false
  become: true
  become_user: postgres
  tags:
    - postgres

- name: Create database
  postgresql_db:
    name: '{{ synapse_db }}'
    owner: '{{ synapse_db_user }}'
  become: true
  become_user: postgres
  tags:
    - postgres
