---

- name: Ensure riot-web paths exists
  file:
    path: '{{ riot_path }}/riot-web'
    state: directory
    owner: '{{ riot_user }}'
    group: '{{ riot_user }}'
    mode: 0755

- name: Download riot-web
  unarchive:
    src: '{{ riot_web_repo }}'
    dest: '{{ riot_path }}'
    remote_src: true
    extra_opts: '--strip-components=1'
    owner: '{{ riot_user }}'
    group: '{{ riot_user }}'

# - name: Riot-web configs
#   template:
#     src: matrix.yml.j2
#     dest: '{{ riot_web_path }}'
#   become: true
#   become_user: '{{ riot_user }}'
