---

- name: Clone git repo matrix-appservice-slack
  git:
    accept_hostkey: true
    repo: '{{ matrix_slack_repo }}'
    dest: '{{ matrix_slack_web_path }}'
  become: true
  become_user: '{{ riot_user }}'

- name: NPM install
  npm:
    path: '{{ matrix_slack_web_path }}'
  environment:
    '{{ riot_web_env }}'
  become: true
  become_user: '{{ riot_user }}'

- name: Slack bridge configuration
  template:
    src: config.yaml.j2
    dest: '{{ matrix_slack_web_path }}/config/config.yaml'
    owner: '{{ riot_user }}'
    group: '{{ riot_user }}'
    mode: 0775

- name: Generate the appservice registration file
  shell: node app.js -r -c config/config.yaml -u "http://localhost:8080"
  environment:
    '{{ riot_web_env }}'
  args:
    chdir: '{{ matrix_slack_web_path }}'
    creates: slack-registration.yaml
  become: true
  become_user: '{{ riot_user }}'

- name: Systemd slack bridge
  template:
    src: slackbridge.service.j2
    dest: /etc/systemd/system/slackbridge.service

- name: Enable slackbridge service
  service:
    name: slackbridge
    enabled: true

- name: Start slackbridge service
  service:
    name: slackbridge
    state: started
