---

- name: Install synapse
  pip:
    name: '{{ synapse_repo }}'
    virtualenv: '{{ synapse_virtual_env }}'
  become: true
  become_user: '{{ riot_user }}'

- name: Generate homeserver config file
  # yamllint disable-line rule:line-length
  shell: '. bin/activate && python -m synapse.app.homeserver --server-name {{ synapse_hostname }} --config-path homeserver.yaml --generate-config --report-stats=yes'
  args:
    chdir: '{{ synapse_virtual_env }}'
    creates: '{{ synapse_virtual_env }}/homeserver.yaml'

- name: Configure homeserver
  template:
    src: homeserver.yaml.j2
    dest: '{{ synapse_virtual_env }}/homeserver.yaml'
  with_items:
    - '{{ synapse_config }}'
