---

- name: Install synapse
  pip:
    name: '{{ synapse_repo }}'
    virtualenv: '{{ synapse_virtualenv }}'
  become: true
  become_user: '{{ riot_user }}'

- name: PIP to install needed dependencies into virtualenv
  pip:
    name: '{{ item }}'
    virtualenv: '{{ synapse_virtualenv }}'
  with_items:
    - characteristic
    - psycopg2
    - psycopg2-binary

- name: Generate homeserver config file
  # yamllint disable-line rule:line-length
  shell: '. bin/activate && python -m synapse.app.homeserver --server-name {{ synapse_hostname }} --config-path homeserver.yaml --generate-config --report-stats=no'
  args:
    chdir: '{{ synapse_virtualenv }}'
    creates: '{{ synapse_virtualenv }}/homeserver.yaml'
  become: true
  become_user: '{{ riot_user }}'

- name: Configure homeserver
  template:
    src: homeserver.yaml.j2
    dest: '{{ synapse_virtualenv }}/homeserver.yaml'
  with_items:
    - '{{ synapse_config }}'
  become: true
  become_user: '{{ riot_user }}'

- name: Configure homeserver log
  template:
    src: logging.yaml.j2
    dest: '{{ synapse_virtualenv }}/logging.log'
  become: true
  become_user: '{{ riot_user }}'

- name: Systemd synapse
  template:
    src: synapse.service.j2
    dest: /etc/systemd/system/synapse.service

- name: Force systemd to reload configs
  systemd:
    daemon_reload: true

- name: Enable synapse services
  service:
    name: synapse
    enabled: true

- name: Start synapse
  service:
    name: synapse
    state: started
