---

- name: Register new matrix user
  become: true
  become_user: '{{ riot_user }}'
  shell: >
    echo {{ item.admin|ternary('yes', 'no') }} | ./bin/register_new_matrix_user
    -c homeserver.yaml -u {{ item.name }}
    -p {{ item.password }} https://{{ synapse_hostname }}:8448
  args:
    chdir: '{{ synapse_virtualenv }}'
  with_items:
    - '{{ synapse_matrix_user }}'
  register: new_users
  # yamllint disable-line rule:line-length
  failed_when: new_users.rc > 0 and 'User ID already taken' not in new_users.stdout
  changed_when: new_users.rc == 0
